# Assignment 1, 8-Puzzle Programming

Your homework must be implemented in this Notebook file. 
You can add as many cells as you want. However, you are not allowed to touch the code below the line "=============".
You need to implement the three (four for grads) searching functions and the print result functions.
For the searching functions, feel free to customize the return data types and parameter lists as long as the function name is as required.


In [19]:
#implementation of function "Iterative_deepening_DFS"

import numpy as np
import time
goal_state = np.array([[0, 1, 2],
                       [3, 4, 5],
                       [6, 7, 8]])
class Node_DFS:
    def __init__(self,data,parent,cost_of_step):
        self.data = data
        self.Left = None
        self.Bottom = None
        self.Right = None
        self.Top = None
        self.parent = parent
        self.cost_of_step = cost_of_step
    
    def option_Left(self):
        index_zero=np.where(self.data == 0)
        if index_zero[1] == 0:
            return False
        else:
            temp = self.data[index_zero[0],index_zero[1]-1]
            next_state = self.data.copy()
            next_state[index_zero[0],index_zero[1]] = temp
            next_state[index_zero[0],index_zero[1]-1] = 0
            return next_state,True
       
    
    def option_Bottom(self):
        index_zero=np.where(self.data == 0)
        if index_zero[0] == 2:
            return False
        else:
            temp = self.data[index_zero[0]+1,index_zero[1]]
            next_state = self.data.copy()
            next_state[index_zero[0],index_zero[1]] = temp
            next_state[index_zero[0]+1,index_zero[1]] = 0
            return next_state,True
        
        
    def option_Right(self):
        index_zero=np.where(self.data == 0)
        if index_zero[1] == 2:
            return False
        else:
            temp = self.data[index_zero[0],index_zero[1]+1]
            next_state = self.data.copy()
            next_state[index_zero[0],index_zero[1]] = temp
            next_state[index_zero[0],index_zero[1]+1] = 0
            return next_state,True
            
    def option_Top(self):
        index_zero=np.where(self.data == 0)
        if index_zero[0] == 0:
            return False
        else:
            temp = self.data[index_zero[0]-1,index_zero[1]]
            next_state = self.data.copy()
            next_state[index_zero[0],index_zero[1]] = temp
            next_state[index_zero[0]-1,index_zero[1]] = 0
            return next_state,True
        
    def IDFS_print(self):
        iterate_count = 0
        for depth in range(100):
        
            queue = [self] 
            frontier = set([]) 
            cutoff = [0]
            queue_depth = [0]
            iterate_count += 1

            while queue:

                current_node = queue.pop(0) 
                #print(current_node.data)
                   
                current_cutoff =cutoff.pop(0)
                current_cost = queue_depth.pop(0)
                
                frontier.add(tuple(current_node.data.reshape(1,9)[0]))

                if np.array_equal(current_node.data,goal_state):
                    steps = current_node.print_result_IDFS()
                    return steps,iterate_count

                else:              
                    if current_cutoff < depth:
                          
                        if current_node.option_Top():
                            next_state,garbage = current_node.option_Top()
                    
                            if tuple(next_state.reshape(1,9)[0]) not in frontier:
                                cost_of_step = current_cost+1
                                current_node.Top = Node_DFS(data=next_state,parent=current_node,cost_of_step=cost_of_step)
                                queue.insert(0,current_node.Top)
                                cutoff.insert(0,current_cutoff+1)
                                queue_depth.insert(0,cost_of_step)

                        if current_node.option_Right():
                            next_state,garbage = current_node.option_Right()
                    
                            if tuple(next_state.reshape(1,9)[0]) not in frontier:
                                cost_of_step = current_cost+1
                                current_node.Right = Node_DFS(data=next_state,parent=current_node,cost_of_step=cost_of_step)
                                queue.insert(0,current_node.Right)
                                cutoff.insert(0,current_cutoff+1)
                                queue_depth.insert(0,cost_of_step)

                        if current_node.option_Bottom():
                            next_state,garbage = current_node.option_Bottom()
                    
                            if tuple(next_state.reshape(1,9)[0]) not in frontier:
                                cost_of_step = current_cost+1
                                current_node.Bottom = Node_DFS(data=next_state,parent=current_node,cost_of_step=cost_of_step)
                                queue.insert(0,current_node.Bottom)
                                cutoff.insert(0,current_cutoff+1)
                                queue_depth.insert(0,cost_of_step)
                                
                                
                        if current_node.option_Left():
                            next_state,garbage = current_node.option_Left()
                    
                            if tuple(next_state.reshape(1,9)[0]) not in frontier:
                                cost_of_step = current_cost+1
                                current_node.Left = Node_DFS(data=next_state,parent=current_node,cost_of_step=cost_of_step)
                                queue.insert(0,current_node.Left)
                                cutoff.insert(0,current_cutoff+1)
                                queue_depth.insert(0,cost_of_step)
                                
    def print_result_IDFS(self):
        data_tracking = [self.data]
        g_tracking = [self.cost_of_step]
        
        while self.parent:
            self = self.parent
            data_tracking.append(self.data)
            g_tracking.append(self.cost_of_step)
            
        print ('Solution of Iterative Deepening Search : ')
        while data_tracking:
            print (data_tracking.pop())
            print ('to') 
        return len(g_tracking)
    
    
    def IDFS_withoutprint(self):
        iterate_count = 0
        for depth in range(100):
        
            queue = [self] 
            frontier = set([]) 
            cutoff = [0]
            queue_depth = [0]
            iterate_count += 1

            while queue:

                current_node = queue.pop(0) 
                #print(current_node.data)
                   
                current_cutoff =cutoff.pop(0)
                current_cost = queue_depth.pop(0)
                
                frontier.add(tuple(current_node.data.reshape(1,9)[0]))

                if np.array_equal(current_node.data,goal_state):
                    steps = current_node.without_result_IDFS()
                    return steps,iterate_count

                else:              
                    if current_cutoff < depth:
                          
                        if current_node.option_Top():
                            next_state,garbage = current_node.option_Top()
                    
                            if tuple(next_state.reshape(1,9)[0]) not in frontier:
                                cost_of_step = current_cost+1
                                current_node.Top = Node_DFS(data=next_state,parent=current_node,cost_of_step=cost_of_step)
                                queue.insert(0,current_node.Top)
                                cutoff.insert(0,current_cutoff+1)
                                queue_depth.insert(0,cost_of_step)

                        if current_node.option_Right():
                            next_state,garbage = current_node.option_Right()
                    
                            if tuple(next_state.reshape(1,9)[0]) not in frontier:
                                cost_of_step = current_cost+1
                                current_node.Right = Node_DFS(data=next_state,parent=current_node,cost_of_step=cost_of_step)
                                queue.insert(0,current_node.Right)
                                cutoff.insert(0,current_cutoff+1)
                                queue_depth.insert(0,cost_of_step)
                               

                        if current_node.option_Bottom():
                            next_state,garbage = current_node.option_Bottom()
                    
                            if tuple(next_state.reshape(1,9)[0]) not in frontier:
                                cost_of_step = current_cost+1
                                current_node.Bottom = Node_DFS(data=next_state,parent=current_node,cost_of_step=cost_of_step)
                                queue.insert(0,current_node.Bottom)
                                cutoff.insert(0,current_cutoff+1)
                                queue_depth.insert(0,cost_of_step)
                                
                                
                        if current_node.option_Left():
                            next_state,garbage = current_node.option_Left()
                    
                            if tuple(next_state.reshape(1,9)[0]) not in frontier:
                                cost_of_step = current_cost+1
                                current_node.Left = Node_DFS(data=next_state,parent=current_node,cost_of_step=cost_of_step)
                                queue.insert(0,current_node.Left)
                                cutoff.insert(0,current_cutoff+1)
                                queue_depth.insert(0,cost_of_step)
                                
                                
    def without_result_IDFS(self):
        g_tracking = [self.cost_of_step]
        
        while self.parent:
            self = self.parent
            g_tracking.append(self.cost_of_step)
            
        return len(g_tracking)



In [20]:
#implementation of function "aStarMisplacedTiles"

import numpy as np
import time
goal_state = np.array([[0, 1, 2],
                       [3, 4, 5],
                       [6, 7, 8]])
class Node_astar_misplaced:
    def __init__(self,data,parent,cost_of_step,heuristic_cost):
        self.data = data
        self.parent = parent
        self.cost_of_step = cost_of_step
        self.heuristic_cost = heuristic_cost
        self.Left = None
        self.Bottom = None
        self.Right = None
        self.Top = None
    
    def option_Left(self):
        index_zero=np.where(self.data == 0)
        if index_zero[1] == 0:
            return False
        else:
            temp = self.data[index_zero[0],index_zero[1]-1]
            next_state = self.data.copy()
            next_state[index_zero[0],index_zero[1]] = temp
            next_state[index_zero[0],index_zero[1]-1] = 0
            return next_state,True
       
    
    def option_Bottom(self):
        index_zero=np.where(self.data == 0)
        if index_zero[0] == 2:
            return False
        else:
            temp = self.data[index_zero[0]+1,index_zero[1]]
            next_state = self.data.copy()
            next_state[index_zero[0],index_zero[1]] = temp
            next_state[index_zero[0]+1,index_zero[1]] = 0
            return next_state,True
        
        
    def option_Right(self):
        index_zero=np.where(self.data == 0)
        if index_zero[1] == 2:
            return False
        else:
            temp = self.data[index_zero[0],index_zero[1]+1]
            next_state = self.data.copy()
            next_state[index_zero[0],index_zero[1]] = temp
            next_state[index_zero[0],index_zero[1]+1] = 0
            return next_state,True
            
    def option_Top(self):
        index_zero=np.where(self.data == 0)
        if index_zero[0] == 0:
            return False
        else:
            temp = self.data[index_zero[0]-1,index_zero[1]]
            next_state = self.data.copy()
            next_state[index_zero[0],index_zero[1]] = temp
            next_state[index_zero[0]-1,index_zero[1]] = 0
            return next_state,True
        
    def astar_misplaced_print(self):
        
        queue = [(self,0)] 
        frontier = set([])
        queue_depth = [(0,0)]
        iterate_count = 0
            

        while queue:
                queue = sorted(queue, key=lambda x:x[1])
                current_node = queue.pop(0)[0]
                queue_depth = sorted(queue_depth, key=lambda x:x[1])
                current_cost = queue_depth.pop(0)[0]
                #print(current_node.data)
                
                frontier.add(tuple(current_node.data.reshape(1,9)[0]))
                iterate_count += 1
            
                if np.array_equal(current_node.data,goal_state):
                    steps=current_node.print_result_astar_misplaced()
                    return steps,iterate_count

                else:              
                    if current_node.option_Top():
                        next_state,garbage = current_node.option_Top()
                        if tuple(next_state.reshape(1,9)[0]) not in frontier:
                            cost_of_step = current_cost+1
                            temp_h=np.sum(next_state!=goal_state)
                            total_cost = temp_h + cost_of_step
                            current_node.Top = Node_astar_misplaced(data=next_state,parent=current_node,cost_of_step=cost_of_step,heuristic_cost=temp_h)
                            queue.append((current_node.Top,total_cost))
                            queue_depth.append((cost_of_step,total_cost))

                    if current_node.option_Right():
                        next_state,garbage = current_node.option_Right()
                        if tuple(next_state.reshape(1,9)[0]) not in frontier:
                            cost_of_step = current_cost+1
                            temp_h=np.sum(next_state!=goal_state)
                            total_cost = temp_h + cost_of_step
                            current_node.Right = Node_astar_misplaced(data=next_state,parent=current_node,cost_of_step=cost_of_step,heuristic_cost=temp_h)
                            queue.append((current_node.Right,total_cost))
                            queue_depth.append((cost_of_step,total_cost))                               

                    if current_node.option_Bottom():
                        next_state,garbage = current_node.option_Bottom()
                        if tuple(next_state.reshape(1,9)[0]) not in frontier:
                            cost_of_step = current_cost+1
                            temp_h=np.sum(next_state!=goal_state)
                            total_cost = temp_h + cost_of_step 
                            current_node.Bottom = Node_astar_misplaced(data=next_state,parent=current_node,cost_of_step=cost_of_step,heuristic_cost=temp_h)
                            queue.append((current_node.Bottom,total_cost))
                            queue_depth.append((cost_of_step,total_cost))
                                
                    if current_node.option_Left():
                        next_state,garbage = current_node.option_Left()
                        if tuple(next_state.reshape(1,9)[0]) not in frontier:
                            cost_of_step = current_cost+1
                            temp_h=np.sum(next_state!=goal_state)
                            total_cost = temp_h + cost_of_step
                            current_node.Left = Node_astar_misplaced(data=next_state,parent=current_node,cost_of_step=cost_of_step,heuristic_cost=temp_h)
                            queue.append((current_node.Left,total_cost))
                            queue_depth.append((cost_of_step,total_cost))
                                
                                
    def print_result_astar_misplaced(self):
        data_tracking = [self.data]
        g_tracking = [self.cost_of_step]
        
        while self.parent:
            self = self.parent
            data_tracking.append(self.data)
            
            g_tracking.append(self.cost_of_step)
        print ('Solution of astr_misplaced : ')
        
        while data_tracking:
            print (data_tracking.pop())
            #print(g_tracking.pop())
            print ('to') 
            
        return len(g_tracking)
    
    
    def astar_misplaced_withoutprint(self):
        
        queue = [(self,0)] 
        frontier = set([])
        queue_depth = [(0,0)]
        iterate_count = 0
            

        while queue:
                queue = sorted(queue, key=lambda x:x[1])
                current_node = queue.pop(0)[0]
                queue_depth = sorted(queue_depth, key=lambda x:x[1])
                current_cost = queue_depth.pop(0)[0]
                #print(current_node.data)
                
                frontier.add(tuple(current_node.data.reshape(1,9)[0]))
                iterate_count += 1

                if np.array_equal(current_node.data,goal_state):
                    steps=current_node.without_result_astar_misplaced()
                    return steps,iterate_count

                else:              
                    if current_node.option_Top():
                        next_state,garbage = current_node.option_Top()
                        if tuple(next_state.reshape(1,9)[0]) not in frontier:
                            cost_of_step = current_cost+1
                            temp_h=np.sum(next_state!=goal_state)
                            total_cost = temp_h + cost_of_step
                            current_node.Top = Node_astar_misplaced(data=next_state,parent=current_node,cost_of_step=cost_of_step,heuristic_cost=temp_h)
                            queue.append((current_node.Top,total_cost))
                            queue_depth.append((cost_of_step,total_cost))

                    if current_node.option_Right():
                        next_state,garbage = current_node.option_Right()
                        if tuple(next_state.reshape(1,9)[0]) not in frontier:
                            cost_of_step = current_cost+1
                            temp_h=np.sum(next_state!=goal_state)
                            total_cost = temp_h + cost_of_step
                            current_node.Right = Node_astar_misplaced(data=next_state,parent=current_node,cost_of_step=cost_of_step,heuristic_cost=temp_h)
                            queue.append((current_node.Right,total_cost))
                            queue_depth.append((cost_of_step,total_cost))                               

                    if current_node.option_Bottom():
                        next_state,garbage = current_node.option_Bottom()
                        if tuple(next_state.reshape(1,9)[0]) not in frontier:
                            cost_of_step = current_cost+1
                            temp_h=np.sum(next_state!=goal_state)
                            total_cost = temp_h + cost_of_step 
                            current_node.Bottom = Node_astar_misplaced(data=next_state,parent=current_node,cost_of_step=cost_of_step,heuristic_cost=temp_h)
                            queue.append((current_node.Bottom,total_cost))
                            queue_depth.append((cost_of_step,total_cost))
                                
                    if current_node.option_Left():
                        next_state,garbage = current_node.option_Left()
                        if tuple(next_state.reshape(1,9)[0]) not in frontier:
                            cost_of_step = current_cost+1
                            temp_h=np.sum(next_state!=goal_state)
                            total_cost = temp_h + cost_of_step
                            current_node.Left = Node_astar_misplaced(data=next_state,parent=current_node,cost_of_step=cost_of_step,heuristic_cost=temp_h)
                            queue.append((current_node.Left,total_cost))
                            queue_depth.append((cost_of_step,total_cost))
                                
                                
    def without_result_astar_misplaced(self):
        g_tracking = [self.cost_of_step]
        
        while self.parent:
            self = self.parent
            g_tracking.append(self.cost_of_step)
            
        return len(g_tracking)



In [21]:
#implementation of function "aStarManhattanDistance"


import numpy as np
import time
goal_state = np.array([[0, 1, 2],
                       [3, 4, 5],
                       [6, 7, 8]])
class Node_astar_manhattan:
    def __init__(self,data,parent,cost_of_step,heuristic_cost):
        self.data = data
        self.parent = parent
        self.cost_of_step = cost_of_step
        self.heuristic_cost = heuristic_cost
        self.Left = None
        self.Bottom = None
        self.Right = None
        self.Top = None
    
    def option_Left(self):
        index_zero=np.where(self.data == 0)
        if index_zero[1] == 0:
            return False
        else:
            temp = self.data[index_zero[0],index_zero[1]-1]
            next_state = self.data.copy()
            next_state[index_zero[0],index_zero[1]] = temp
            next_state[index_zero[0],index_zero[1]-1] = 0
            return next_state,True
       
    
    def option_Bottom(self):
        index_zero=np.where(self.data == 0)
        if index_zero[0] == 2:
            return False
        else:
            temp = self.data[index_zero[0]+1,index_zero[1]]
            next_state = self.data.copy()
            next_state[index_zero[0],index_zero[1]] = temp
            next_state[index_zero[0]+1,index_zero[1]] = 0
            return next_state,True
        
        
    def option_Right(self):
        index_zero=np.where(self.data == 0)
        if index_zero[1] == 2:
            return False
        else:
            temp = self.data[index_zero[0],index_zero[1]+1]
            next_state = self.data.copy()
            next_state[index_zero[0],index_zero[1]] = temp
            next_state[index_zero[0],index_zero[1]+1] = 0
            return next_state,True
            
    def option_Top(self):
        index_zero=np.where(self.data == 0)
        if index_zero[0] == 0:
            return False
        else:
            temp = self.data[index_zero[0]-1,index_zero[1]]
            next_state = self.data.copy()
            next_state[index_zero[0],index_zero[1]] = temp
            next_state[index_zero[0]-1,index_zero[1]] = 0
            return next_state,True
        
    def astar_manhattan_print(self):
        
        queue = [(self,0)] 
        frontier = set([])
        queue_depth = [(0,0)]
        iterate_count = 0
        
            

        while queue:
                queue = sorted(queue, key=lambda x:x[1])
                current_node = queue.pop(0)[0]
                queue_depth = sorted(queue_depth, key=lambda x:x[1])
                current_cost = queue_depth.pop(0)[0]
                #print(current_node.data)
                
                frontier.add(tuple(current_node.data.reshape(1,9)[0]))
                iterate_count += 1

                if np.array_equal(current_node.data,goal_state):
                    steps=current_node.print_result_astar_manhattan()
                    return steps,iterate_count

                else:              
                    if current_node.option_Top():
                        next_state,garbage = current_node.option_Top()
                        if tuple(next_state.reshape(1,9)[0]) not in frontier:
                            cost_of_step = current_cost+1
                            temp = next_state
                            goal_position_dic = {0:(0,0),1:(0,1),2:(0,2),3:(1,0),4:(1,1),5:(1,2),6:(2,0),7:(2,1),8:(2,2)}
                            temp_h=0
                            for i in range(3):
                                for j in range(3):
                                    if temp[i,j] != 0:
                                        temp_h += sum(abs(a-b) for a,b in zip((i,j), goal_position_dic[temp[i,j]]))
                                        
                            total_cost = temp_h + cost_of_step
                            current_node.Top = Node_astar_manhattan(data=next_state,parent=current_node,cost_of_step=cost_of_step,heuristic_cost=temp_h)
                            queue.append((current_node.Top,total_cost))
                            queue_depth.append((cost_of_step,total_cost))

                    if current_node.option_Right():
                        next_state,garbage = current_node.option_Right()
                        if tuple(next_state.reshape(1,9)[0]) not in frontier:
                            cost_of_step = current_cost+1
                            temp = next_state
                            goal_position_dic = {0:(0,0),1:(0,1),2:(0,2),3:(1,0),4:(1,1),5:(1,2),6:(2,0),7:(2,1),8:(2,2)}
                            temp_h=0
                            for i in range(3):
                                for j in range(3):
                                    if temp[i,j] != 0:
                                        temp_h += sum(abs(a-b) for a,b in zip((i,j), goal_position_dic[temp[i,j]]))
                                        
                            total_cost = temp_h + cost_of_step
                            current_node.Right = Node_astar_manhattan(data=next_state,parent=current_node,cost_of_step=cost_of_step,heuristic_cost=temp_h)
                            queue.append((current_node.Right,total_cost))
                            queue_depth.append((cost_of_step,total_cost))                               

                    if current_node.option_Bottom():
                        next_state,garbage = current_node.option_Bottom()
                        if tuple(next_state.reshape(1,9)[0]) not in frontier:
                            cost_of_step = current_cost+1
                            temp = next_state
                            goal_position_dic = {0:(0,0),1:(0,1),2:(0,2),3:(1,0),4:(1,1),5:(1,2),6:(2,0),7:(2,1),8:(2,2)}
                            temp_h=0
                            for i in range(3):
                                for j in range(3):
                                    if temp[i,j] != 0:
                                        temp_h += sum(abs(a-b) for a,b in zip((i,j), goal_position_dic[temp[i,j]]))
                            
                            total_cost = temp_h + cost_of_step 
                            current_node.Bottom = Node_astar_manhattan(data=next_state,parent=current_node,cost_of_step=cost_of_step,heuristic_cost=temp_h)
                            queue.append((current_node.Bottom,total_cost))
                            queue_depth.append((cost_of_step,total_cost))
                                
                    if current_node.option_Left():
                        next_state,garbage = current_node.option_Left()
                        if tuple(next_state.reshape(1,9)[0]) not in frontier:
                            cost_of_step = current_cost+1
                            temp = next_state
                            goal_position_dic = {0:(0,0),1:(0,1),2:(0,2),3:(1,0),4:(1,1),5:(1,2),6:(2,0),7:(2,1),8:(2,2)}
                            temp_h=0
                            for i in range(3):
                                for j in range(3):
                                    if temp[i,j] != 0:
                                        temp_h += sum(abs(a-b) for a,b in zip((i,j), goal_position_dic[temp[i,j]]))
                            
                            total_cost = temp_h + cost_of_step
                            current_node.Left = Node_astar_manhattan(data=next_state,parent=current_node,cost_of_step=cost_of_step,heuristic_cost=temp_h)
                            queue.append((current_node.Left,total_cost))
                            queue_depth.append((cost_of_step,total_cost))
                                
                                
    def print_result_astar_manhattan(self):
        data_tracking = [self.data]
        g_tracking = [self.cost_of_step]
        
        while self.parent:
            self = self.parent
            data_tracking.append(self.data)
            g_tracking.append(self.cost_of_step)
        print ('Solution of astar_manhattan : ')
        
        while data_tracking:
            print (data_tracking.pop())
            print ('to')      
        return len(g_tracking)
    
    def astar_manhattan_withoutprint(self):
        
        queue = [(self,0)] 
        frontier = set([])
        queue_depth = [(0,0)]
        iterate_count = 0
        
            

        while queue:
                queue = sorted(queue, key=lambda x:x[1])
                current_node = queue.pop(0)[0]
                queue_depth = sorted(queue_depth, key=lambda x:x[1])
                current_cost = queue_depth.pop(0)[0]
                #print(current_node.data)
                
                frontier.add(tuple(current_node.data.reshape(1,9)[0]))
                iterate_count += 1

                if np.array_equal(current_node.data,goal_state):
                    steps=current_node.without_result_astar_manhattan()
                    return steps,iterate_count

                else:              
                    if current_node.option_Top():
                        next_state,garbage = current_node.option_Top()
                        if tuple(next_state.reshape(1,9)[0]) not in frontier:
                            cost_of_step = current_cost+1
                            temp = next_state
                            goal_position_dic = {0:(0,0),1:(0,1),2:(0,2),3:(1,0),4:(1,1),5:(1,2),6:(2,0),7:(2,1),8:(2,2)}
                            temp_h=0
                            for i in range(3):
                                for j in range(3):
                                    if temp[i,j] != 0:
                                        temp_h += sum(abs(a-b) for a,b in zip((i,j), goal_position_dic[temp[i,j]]))
                                        
                            total_cost = temp_h + cost_of_step
                            current_node.Top = Node_astar_manhattan(data=next_state,parent=current_node,cost_of_step=cost_of_step,heuristic_cost=temp_h)
                            queue.append((current_node.Top,total_cost))
                            queue_depth.append((cost_of_step,total_cost))

                    if current_node.option_Right():
                        next_state,garbage = current_node.option_Right()
                        if tuple(next_state.reshape(1,9)[0]) not in frontier:
                            cost_of_step = current_cost+1
                            temp = next_state
                            goal_position_dic = {0:(0,0),1:(0,1),2:(0,2),3:(1,0),4:(1,1),5:(1,2),6:(2,0),7:(2,1),8:(2,2)}
                            temp_h=0
                            for i in range(3):
                                for j in range(3):
                                    if temp[i,j] != 0:
                                        temp_h += sum(abs(a-b) for a,b in zip((i,j), goal_position_dic[temp[i,j]]))
                                        
                            total_cost = temp_h + cost_of_step
                            current_node.Right = Node_astar_manhattan(data=next_state,parent=current_node,cost_of_step=cost_of_step,heuristic_cost=temp_h)
                            queue.append((current_node.Right,total_cost))
                            queue_depth.append((cost_of_step,total_cost))                               

                    if current_node.option_Bottom():
                        next_state,garbage = current_node.option_Bottom()
                        if tuple(next_state.reshape(1,9)[0]) not in frontier:
                            cost_of_step = current_cost+1
                            temp = next_state
                            goal_position_dic = {0:(0,0),1:(0,1),2:(0,2),3:(1,0),4:(1,1),5:(1,2),6:(2,0),7:(2,1),8:(2,2)}
                            temp_h=0
                            for i in range(3):
                                for j in range(3):
                                    if temp[i,j] != 0:
                                        temp_h += sum(abs(a-b) for a,b in zip((i,j), goal_position_dic[temp[i,j]]))
                            
                            total_cost = temp_h + cost_of_step 
                            current_node.Bottom = Node_astar_manhattan(data=next_state,parent=current_node,cost_of_step=cost_of_step,heuristic_cost=temp_h)
                            queue.append((current_node.Bottom,total_cost))
                            queue_depth.append((cost_of_step,total_cost))
                                
                    if current_node.option_Left():
                        next_state,garbage = current_node.option_Left()
                        if tuple(next_state.reshape(1,9)[0]) not in frontier:
                            cost_of_step = current_cost+1
                            temp = next_state
                            goal_position_dic = {0:(0,0),1:(0,1),2:(0,2),3:(1,0),4:(1,1),5:(1,2),6:(2,0),7:(2,1),8:(2,2)}
                            temp_h=0
                            for i in range(3):
                                for j in range(3):
                                    if temp[i,j] != 0:
                                        temp_h += sum(abs(a-b) for a,b in zip((i,j), goal_position_dic[temp[i,j]]))
                            
                            total_cost = temp_h + cost_of_step
                            current_node.Left = Node_astar_manhattan(data=next_state,parent=current_node,cost_of_step=cost_of_step,heuristic_cost=temp_h)
                            queue.append((current_node.Left,total_cost))
                            queue_depth.append((cost_of_step,total_cost))
                                
                                
    def without_result_astar_manhattan(self):
        g_tracking = [self.cost_of_step]
        
        while self.parent:
            self = self.parent
            g_tracking.append(self.cost_of_step)
        
        return len(g_tracking)


In [22]:
#implementation of function "breadthFirstSearch" (for graduate students)

import numpy as np
import time
goal_state = np.array([[0, 1, 2],
                       [3, 4, 5],
                       [6, 7, 8]])
class Node_BFS:
    def __init__(self,data,parent,cost_of_step):
        self.data = data
        self.Left = None
        self.Bottom = None
        self.Right = None
        self.Top = None
        self.parent = parent
        self.cost_of_step = cost_of_step
    
    def option_Left(self):
        index_zero=np.where(self.data == 0)
        if index_zero[1] == 0:
            return False
        else:
            temp = self.data[index_zero[0],index_zero[1]-1]
            next_state = self.data.copy()
            next_state[index_zero[0],index_zero[1]] = temp
            next_state[index_zero[0],index_zero[1]-1] = 0
            return next_state,True
       
    
    def option_Bottom(self):
        index_zero=np.where(self.data == 0)
        if index_zero[0] == 2:
            return False
        else:
            temp = self.data[index_zero[0]+1,index_zero[1]]
            next_state = self.data.copy()
            next_state[index_zero[0],index_zero[1]] = temp
            next_state[index_zero[0]+1,index_zero[1]] = 0
            return next_state,True
        
        
    def option_Right(self):
        index_zero=np.where(self.data == 0)
        if index_zero[1] == 2:
            return False
        else:
            temp = self.data[index_zero[0],index_zero[1]+1]
            next_state = self.data.copy()
            next_state[index_zero[0],index_zero[1]] = temp
            next_state[index_zero[0],index_zero[1]+1] = 0
            return next_state,True
            
    def option_Top(self):
        index_zero=np.where(self.data == 0)
        if index_zero[0] == 0:
            return False
        else:
            temp = self.data[index_zero[0]-1,index_zero[1]]
            next_state = self.data.copy()
            next_state[index_zero[0],index_zero[1]] = temp
            next_state[index_zero[0]-1,index_zero[1]] = 0
            return next_state,True
        
    def BFS_print(self):
    
            queue = [self] 
            frontier = set([]) 
            iterate_count = 0
            queue_depth = [0]
            while queue:

                current_node = queue.pop(0) 
                current_cost = queue_depth.pop(0)
                #print(current_node.data)
                   
                frontier.add(tuple(current_node.data.reshape(1,9)[0]))
                iterate_count += 1

                if np.array_equal(current_node.data,goal_state):
                    steps = current_node.print_result_BFS()
                    return steps,iterate_count

                else:              
                        if current_node.option_Top():
                            next_state,garbage = current_node.option_Top()
                    
                            if tuple(next_state.reshape(1,9)[0]) not in frontier:
                                cost_of_step = current_cost+1
                                current_node.Top = Node_BFS(data=next_state,parent=current_node,cost_of_step=cost_of_step)
                                queue.append(current_node.Top)
                                queue_depth.append(cost_of_step)

                        if current_node.option_Right():
                            next_state,garbage = current_node.option_Right()
                    
                            if tuple(next_state.reshape(1,9)[0]) not in frontier:
                                cost_of_step = current_cost+1
                                current_node.Right = Node_BFS(data=next_state,parent=current_node,cost_of_step=cost_of_step)
                                queue.append(current_node.Right)
                                queue_depth.append(cost_of_step)
                               

                        if current_node.option_Bottom():
                            next_state,garbage = current_node.option_Bottom()
                    
                            if tuple(next_state.reshape(1,9)[0]) not in frontier:
                                cost_of_step = current_cost+1
                                current_node.Bottom = Node_BFS(data=next_state,parent=current_node,cost_of_step=cost_of_step)
                                queue.append(current_node.Bottom)
                                queue_depth.append(cost_of_step)
                                
                                
                        if current_node.option_Left():
                            next_state,garbage = current_node.option_Left()
                    
                            if tuple(next_state.reshape(1,9)[0]) not in frontier:
                                cost_of_step = current_cost+1
                                current_node.Left = Node_BFS(data=next_state,parent=current_node,cost_of_step=cost_of_step)
                                queue.append(current_node.Left)
                                queue_depth.append(cost_of_step)
                                
                                
    def print_result_BFS(self):
        data_tracking = [self.data]
        g_tracking = [self.cost_of_step]
        
        while self.parent:
            self = self.parent
            data_tracking.append(self.data)
            g_tracking.append(self.cost_of_step)
            
        print ('Solution of Breadth First Search : ')
        while data_tracking:
            print (data_tracking.pop())
            print ('to')           
        return len(g_tracking)
    
    
    def BFS_withoutprint(self):
    
            queue = [self] 
            frontier = set([]) 
            iterate_count = 0
            queue_depth = [0]
            while queue:

                current_node = queue.pop(0) 
                current_cost = queue_depth.pop(0)
                #print(current_node.data)
                   
                frontier.add(tuple(current_node.data.reshape(1,9)[0]))
                iterate_count += 1

                if np.array_equal(current_node.data,goal_state):
                    steps = current_node.withoutprint_result_BFS()
                    return steps,iterate_count

                else:              
                        if current_node.option_Top():
                            next_state,garbage = current_node.option_Top()
                    
                            if tuple(next_state.reshape(1,9)[0]) not in frontier:
                                cost_of_step = current_cost+1
                                current_node.Top = Node_BFS(data=next_state,parent=current_node,cost_of_step=cost_of_step)
                                queue.append(current_node.Top)
                                queue_depth.append(cost_of_step)

                        if current_node.option_Right():
                            next_state,garbage = current_node.option_Right()
                    
                            if tuple(next_state.reshape(1,9)[0]) not in frontier:
                                cost_of_step = current_cost+1
                                current_node.Right = Node_BFS(data=next_state,parent=current_node,cost_of_step=cost_of_step)
                                queue.append(current_node.Right)
                                queue_depth.append(cost_of_step)
                               

                        if current_node.option_Bottom():
                            next_state,garbage = current_node.option_Bottom()
                    
                            if tuple(next_state.reshape(1,9)[0]) not in frontier:
                                cost_of_step = current_cost+1
                                current_node.Bottom = Node_BFS(data=next_state,parent=current_node,cost_of_step=cost_of_step)
                                queue.append(current_node.Bottom)
                                queue_depth.append(cost_of_step)
                                
                                
                        if current_node.option_Left():
                            next_state,garbage = current_node.option_Left()
                    
                            if tuple(next_state.reshape(1,9)[0]) not in frontier:
                                cost_of_step = current_cost+1
                                current_node.Left = Node_BFS(data=next_state,parent=current_node,cost_of_step=cost_of_step)
                                queue.append(current_node.Left)
                                queue_depth.append(cost_of_step)
                                
                                
    def withoutprint_result_BFS(self):
        g_tracking = [self.cost_of_step]
        
        while self.parent:
            self = self.parent
            g_tracking.append(self.cost_of_step)
                  
        return len(g_tracking)


In [23]:
#implementation of function "print_result(result)"

def print_result():
    #for Iterative_DFS
    file = open("Input8PuzzleCases.txt")
    cases=[]
    index=0
    for line in file:
        string=line.strip("\n").split(",")
        cases.append([])
        for j in range (len(string)):
            cases[index].append(int(string[j]))
        index+=1

    time_spend_IDFS = []
    steps_track_IDFS=[]
    iteration_track_IDFS = []

    test = np.array(cases.pop(0)).reshape((3,3))
    root=Node_DFS(data=test,parent=None,cost_of_step=0)

    start = time.time()
    steps,iterate_count = root.IDFS_print()
    time_spend_IDFS.append(time.time()-start)
    steps_track_IDFS.append(steps)
    iteration_track_IDFS.append(iterate_count)

    for i in range(99):

        test = np.array(cases.pop(0)).reshape((3,3))
        root=Node_DFS(data=test,parent=None,cost_of_step=0)

        start = time.time()
        steps,iterate_count = root.IDFS_withoutprint()
        time_spend_IDFS.append(time.time()-start)
        steps_track_IDFS.append(steps)
        iteration_track_IDFS.append(iterate_count)
        
    #FOR ASTAR_MISPLACED
    file = open("Input8PuzzleCases.txt")
    cases=[]
    index=0
    for line in file:
        string=line.strip("\n").split(",")
        cases.append([])
        for j in range (len(string)):
            cases[index].append(int(string[j]))
        index+=1

    time_spend_AstrMis = []
    steps_track_AstrMis=[]
    iteration_track_AstrMis = []

    test = np.array(cases.pop(0)).reshape((3,3))
    root=Node_astar_misplaced(data=test,parent=None,cost_of_step=0,heuristic_cost=0)

    start = time.time()
    steps,iterate_count = root.astar_misplaced_print()
    time_spend_AstrMis.append(time.time()-start)
    steps_track_AstrMis.append(steps)
    iteration_track_AstrMis.append(iterate_count)

    for i in range(99):

        test = np.array(cases.pop(0)).reshape((3,3))
        root=Node_astar_misplaced(data=test,parent=None,cost_of_step=0,heuristic_cost=0)

        start = time.time()
        steps,iterate_count = root.astar_misplaced_withoutprint()
        time_spend_AstrMis.append(time.time()-start)
        steps_track_AstrMis.append(steps)
        iteration_track_AstrMis.append(iterate_count)
        
    # FOR ASTAR_MANHATTAN
    file = open("Input8PuzzleCases.txt")
    cases=[]
    index=0
    for line in file:
        string=line.strip("\n").split(",")
        cases.append([])
        for j in range (len(string)):
            cases[index].append(int(string[j]))
        index+=1

    time_spend_AstrMan = []
    steps_track_AstrMan=[]
    iteration_track_AstrMan = []

    test = np.array(cases.pop(0)).reshape((3,3))
    root=Node_astar_manhattan(data=test,parent=None,cost_of_step=0,heuristic_cost=0)

    start = time.time()
    steps,iterate_count = root.astar_manhattan_print()
    time_spend_AstrMan.append(time.time()-start)
    steps_track_AstrMan.append(steps)
    iteration_track_AstrMan.append(iterate_count)

    for i in range(99):

        test = np.array(cases.pop(0)).reshape((3,3))
        root=Node_astar_manhattan(data=test,parent=None,cost_of_step=0,heuristic_cost=0)

        start = time.time()
        steps,iterate_count = root.astar_manhattan_withoutprint()
        time_spend_AstrMan.append(time.time()-start)
        steps_track_AstrMan.append(steps)
        iteration_track_AstrMan.append(iterate_count)
        
    # FOR BFS
    file = open("Input8PuzzleCases.txt")
    cases=[]
    index=0
    for line in file:
        string=line.strip("\n").split(",")
        cases.append([])
        for j in range (len(string)):
            cases[index].append(int(string[j]))
        index+=1

    time_spend_BFS = []
    steps_track_BFS=[]
    iteration_track_BFS = []

    test = np.array(cases.pop(0)).reshape((3,3))
    root=Node_BFS(data=test,parent=None,cost_of_step=0)

    start = time.time()
    steps,iterate_count = root.BFS_print()
    time_spend_BFS.append(time.time()-start)
    steps_track_BFS.append(steps)
    iteration_track_BFS.append(iterate_count)

    for i in range(19):

        test = np.array(cases.pop(0)).reshape((3,3))
        root=Node_BFS(data=test,parent=None,cost_of_step=0)

        start = time.time()
        steps,iterate_count = root.BFS_withoutprint()
        time_spend_BFS.append(time.time()-start)
        steps_track_BFS.append(steps)
        iteration_track_BFS.append(iterate_count)
        
        
        
    print('\t\t\t Average_Time \t Average_Steps \t Average_Iterations')
    print('\t Iterative DFS \t ', sum(time_spend_IDFS)/100, ' \t ', sum(steps_track_IDFS)/100, ' \t ', sum(iteration_track_IDFS)/100)
    print('\t A*(Misplaced) \t ', sum(time_spend_AstrMis)/100, ' \t ', sum(steps_track_AstrMis)/100, ' \t ', sum(iteration_track_AstrMis)/100)
    print('\t A*(Manhattan) \t ', sum(time_spend_AstrMan)/100, ' \t ', sum(steps_track_AstrMan)/100, ' \t ', sum(iteration_track_AstrMan)/100)
    print('\t BFS \t\t ', sum(time_spend_BFS)/20, ' \t ', sum(steps_track_BFS)/20, ' \t ', sum(iteration_track_BFS)/20)
    
    return time_spend_IDFS,time_spend_AstrMis,time_spend_AstrMan,time_spend_BFS,steps_track_IDFS,steps_track_AstrMis,steps_track_AstrMan,steps_track_BFS,iteration_track_IDFS,iteration_track_AstrMis,iteration_track_AstrMan,iteration_track_BFS


In [24]:
time_spend_IDFS,time_spend_AstrMis,time_spend_AstrMan,time_spend_BFS,steps_track_IDFS,steps_track_AstrMis,steps_track_AstrMan,steps_track_BFS,iteration_track_IDFS,iteration_track_AstrMis,iteration_track_AstrMan,iteration_track_BFS = print_result()

Solution of Iterative Deepening Search : 
[[8 7 5]
 [4 1 2]
 [3 0 6]]
to
[[8 7 5]
 [4 1 2]
 [0 3 6]]
to
[[8 7 5]
 [0 1 2]
 [4 3 6]]
to
[[8 7 5]
 [1 0 2]
 [4 3 6]]
to
[[8 7 5]
 [1 3 2]
 [4 0 6]]
to
[[8 7 5]
 [1 3 2]
 [0 4 6]]
to
[[8 7 5]
 [0 3 2]
 [1 4 6]]
to
[[8 7 5]
 [3 0 2]
 [1 4 6]]
to
[[8 0 5]
 [3 7 2]
 [1 4 6]]
to
[[0 8 5]
 [3 7 2]
 [1 4 6]]
to
[[3 8 5]
 [0 7 2]
 [1 4 6]]
to
[[3 8 5]
 [1 7 2]
 [0 4 6]]
to
[[3 8 5]
 [1 7 2]
 [4 0 6]]
to
[[3 8 5]
 [1 7 2]
 [4 6 0]]
to
[[3 8 5]
 [1 7 0]
 [4 6 2]]
to
[[3 8 5]
 [1 0 7]
 [4 6 2]]
to
[[3 0 5]
 [1 8 7]
 [4 6 2]]
to
[[0 3 5]
 [1 8 7]
 [4 6 2]]
to
[[1 3 5]
 [0 8 7]
 [4 6 2]]
to
[[1 3 5]
 [4 8 7]
 [0 6 2]]
to
[[1 3 5]
 [4 8 7]
 [6 0 2]]
to
[[1 3 5]
 [4 8 7]
 [6 2 0]]
to
[[1 3 5]
 [4 8 0]
 [6 2 7]]
to
[[1 3 5]
 [4 0 8]
 [6 2 7]]
to
[[1 3 5]
 [4 2 8]
 [6 0 7]]
to
[[1 3 5]
 [4 2 8]
 [0 6 7]]
to
[[1 3 5]
 [0 2 8]
 [4 6 7]]
to
[[0 3 5]
 [1 2 8]
 [4 6 7]]
to
[[3 0 5]
 [1 2 8]
 [4 6 7]]
to
[[3 2 5]
 [1 0 8]
 [4 6 7]]
to
[[3 2 5]
 [0 1 8]
 [4 6 7]]


You can insert as many cells as you want above
You are not Allowed to modify the code below this line.
===============================

In [ ]:
#you need to implement print_result function to print out the result according to the required format
print_result(result)


The output format should be as follows. You only need to give one sample solution as an example.
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Solution of the first Scenario:
X X X
X X X
X X X
to
X X X
X X X
X X X
to
X X X
X X X
X X X
to
X X X
X X X
X X X
to
.
.
.
0 1 2
3 4 5
6 7 8

                Average_Steps    Average_Time   Average_Iterations   
UCS
A*(Misplaced)
A*(Manhattan)
BFS

